name: Firebase Hosting Deploy

on:
  push:
    branches: [main]          # deploy whenever you push/merge to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:              # lets the action create deployment statuses
      contents: read
      deployments: write

    steps:
      # 1 – Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4      # latest version  [oai_citation:0‡Julia Programming Language](https://discourse.julialang.org/t/how-do-i-update-github-actions-to-node-js-20/110536?utm_source=chatgpt.com)

      # 2 – Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0   # official action  [oai_citation:2‡GitHub](https://github.com/FirebaseExtended/action-hosting-deploy?utm_source=chatgpt.com)
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}          # auto-provided
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId:              live                                # deploys to the live site
          projectId:              my-firebase-project                 # <-- change this
